name: clang-tidy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-tidy:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-21 cmake ninja-build

      - name: Configure
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -Dtemplate_BUILD_EXAMPLES=ON
            # -Dtemplate_ENABLE_TESTS=ON

      - name: Check clang-tidy
        env:
          CLANG_TIDY: clang-tidy-21
          BUILD_DIR: build
        run: ./scripts/git/check-tidy.sh
