name: clang-format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-21

      - name: Check formatting
        env:
            CLANG_FORMAT: clang-format-21
        run: ./scripts/git/check-format.sh
